[package]
name = "rust-htslib"
version = "0.26.1"
authors = ["Christopher Schröder <christopher.schroeder@tu-dortmund.de>", "Johannes Köster <johannes.koester@tu-dortmund.de>"]
build = "build.rs"
description = "This library provides HTSlib bindings and a high level Rust API for reading and writing BAM files."
readme = "README.md"
keywords = ["htslib", "bam", "bioinformatics", "pileup", "sequencing"]
license = "MIT"
repository = "https://github.com/rust-bio/rust-htslib.git"
documentation = "https://docs.rs/rust-htslib"
edition = "2018"

[package.metadata.release]
pre-release-commit-message = "release version {{version}}"
tag-message = "Version {{version}} of Rust-HTSlib."


[dependencies]
libc = "0.2"
libz-sys = "1.0"
bzip2-sys = { version = "0.1", optional = true }
lzma-sys = { version = "0.1", optional = true }
itertools = "0.8"
newtype_derive = "0.1"
custom_derive = "0.1"
url = "2.1"
ieee754 = "0.2"
lazy_static = "1.4"
bitflags = "1.2"
regex = "1.3"
linear-map = "1.2"
serde_base = { version = "^1", optional = true, package = "serde" }
serde_bytes = { version = "0.11", optional = true }
bio-types = ">=0.5.1"
snafu = ">= 0.5.0, <= 0.6.0"

[features]
default = ["bzip2", "lzma"]
bzip2 = ["bzip2-sys"]
lzma = ["lzma-sys"]
serde = ["serde_base", "serde_bytes"]

[dev-dependencies]
tempdir = "0.3"
bincode = "1.2"
serde_json = "1.0"
pretty_assertions = "0.6"

[build-dependencies]
fs-utils = "1.1"
bindgen = "0.52.0"
cc = "1.0"
glob = "0.3.0"
